FROM alpine

RUN apk add nodejs
RUN apk add npm
RUN apk add python2
RUN apk add python-dev
RUN apk add py-pip
RUN apk add musl-dev
RUN apk add libffi-dev
RUN apk add openssl-dev
RUN apk add go
RUN wget https://github.com/akamai/cli/releases/download/1.1.4/akamai-1.1.4-linux386 -O /usr/local/bin/akamai
RUN chmod +x /usr/local/bin/akamai
RUN mkdir /root/.akamai-cli
COPY config /root/.akamai-cli/config
RUN akamai install property-manager
RUN akamai install purge --force
RUN akamai install auth
RUN akamai install image-manager